Add some sanity checks to push

diff --git a/efidir b/efidir
--- a/efidir
+++ b/efidir
@@ -11,6 +11,13 @@ usage() {
     exit 1
 }
 
+sanity_check() {
+    if [ ! -r "$1" ]; then
+	echo "missing file $1; refusing to push"
+        exit 1
+    fi
+}
+
 if [ $# != 2 ]; then
     usage
 fi
@@ -49,9 +56,11 @@ fi
 dir="${dir%%/}"
 
 # Note that the string "/./" is special to rsync when --relative is used.
-
 if [ "$cmd" == pull ]; then
     rsync --no-perms --times --delete -v --filter "merge $self_dirname/rsync-filter" --recursive --relative "$dir/EFI/./CLOVER" efi
 else
+    sanity_check "efi/CLOVER"
+    sanity_check "efi/CLOVER/config.plist"
+    sanity_check "efi/CLOVER/kexts"
     rsync --no-perms --times --delete -v --filter "merge $self_dirname/rsync-filter" --recursive --relative efi/./CLOVER "$dir/EFI/"
 fi
